spring:
  profiles:
    active:
    - development
  application:
     name: config-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8888  
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          config: DEBUG
          gateway: TRACE  
msg: Hello 
