spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: frontend-path-home
        uri: lb://CART
        predicates:
        - Path=/,/home
      - id: frontend-path-js
        uri: lb://CART
        predicates:
        - Path=/*.*
      - id: backend-path
        uri: lb://CATALOGUE
        predicates:
        - Header=Referer, http://localhost:8080/(.*)
      - id: frontend-path
        uri: lb://CART
        predicates:
        - Path=/**    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE  
 
      


